[package]
name = "godot_vrrop_server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
vrrop_common.workspace = true
vrrop_server.workspace = true

anyhow.workspace = true
godot.workspace = true
image.workspace = true
nalgebra.workspace = true
tokio.workspace = true